import type { Node } from "@prisma/client";
import { getSetting } from "../settings";
import { SETTING_KEYS } from "../constants";
import { env } from "../env";

/**
 * Single source of truth for the daemon's `config.yml`.
 *
 * Rendered in three places, all from here:
 *   - Admin -> Nodes -> node detail (copy/paste)
 *   - GET /api/remote/nodes/config (fetched by `spanel-daemon configure`)
 *   - the Node.js installer, which just writes what the panel returns
 */

export interface DaemonConfigOptions {
  panelUrl: string;
  /** Plaintext node token; already decrypted by the caller. */
  token: string;
  /** Omit the token so the config can be shown without leaking the secret. */
  redactToken?: boolean;
}

/** Resolves the effective panel URL from settings, falling back to env.appUrl. */
export async function resolvePanelUrl(): Promise<string> {
  const override = await getSetting(SETTING_KEYS.panelUrl);
  const port = await getSetting(SETTING_KEYS.panelPort);
  if (override) {
    const base = override.replace(/\/+$/, "");
    if (port) {
      try {
        const url = new URL(base);
        url.port = port;
        return url.toString().replace(/\/+$/, "");
      } catch {
        return `${base}:${port}`;
      }
    }
    return base;
  }
  if (port) {
    try {
      const url = new URL(env.appUrl);
      url.port = port;
      return url.toString().replace(/\/+$/, "");
    } catch {
      return env.appUrl;
    }
  }
  return env.appUrl;
}

function acmeEmailFor(fqdn: string): string {
  const parts = fqdn.split(".");
  const apex = parts.length >= 2 ? parts.slice(-2).join(".") : fqdn;
  return `admin@${apex}`;
}

export function renderDaemonConfig(node: Node, options: DaemonConfigOptions): string {
  // TLS is terminated by the daemon only when it is addressed over https and is
  // not sitting behind a reverse proxy that already holds the certificate.
  const sslEnabled = node.scheme === "https" && !node.behindProxy;

  return `# SPanel daemon configuration — ${node.name}
# Path: /etc/spanel/config.yml   ·   Generated by the panel; safe to regenerate.
debug: false

api:
  host: 0.0.0.0
  port: ${node.daemonPort}
  ssl:
    enabled: ${sslEnabled}
    cert: /etc/letsencrypt/live/${node.fqdn}/fullchain.pem
    key: /etc/letsencrypt/live/${node.fqdn}/privkey.pem
  upload_limit: ${node.uploadSize}

system:
  data: ${node.daemonBase}
  archive_directory: ${node.daemonBase}/.archives
  backup_directory: ${node.daemonBase}/.backups
  tmp_directory: /tmp/spanel
  username: spanel
  timezone: UTC
  sftp:
    bind_port: ${node.daemonSftpPort}

docker:
  network:
    name: spanel0
    driver: bridge
    interface: 172.19.0.1
    dns:
      - 1.1.1.1
      - 8.8.8.8
  install_limit: 5

proxy:
  enabled: ${node.proxyEnabled}
  http_port: ${node.proxyHttpPort}
  https_port: ${node.proxyHttpsPort}
  acme_email: ${acmeEmailFor(node.fqdn)}
  config_directory: /etc/spanel/vhosts
  reload_command: nginx -s reload

remote: ${options.panelUrl}
token_id: ${node.daemonTokenId}
token: ${options.redactToken ? "<hidden — use the install command>" : options.token}
`;
}

/**
 * One-line bootstrap — a single line so it pastes into a terminal in one go
 * (no `\` continuations, which frequently break on paste). The shell part only
 * guarantees curl + Node.js exist; every install step after that runs in Node
 * (see public/install/daemon.mjs).
 */
export function renderInstallCommand(node: Node, options: DaemonConfigOptions): string {
  return `curl -fsSL ${options.panelUrl}/install/daemon.sh | sudo bash -s -- --panel ${options.panelUrl} --token-id ${node.daemonTokenId} --token ${options.token} --port ${node.daemonPort}`;
}

/** Single-line equivalent for when Node.js 20+ is already installed on the machine. */
export function renderNodeInstallCommand(node: Node, options: DaemonConfigOptions): string {
  return `curl -fsSL ${options.panelUrl}/install/daemon.mjs -o /tmp/spanel-install.mjs && sudo node /tmp/spanel-install.mjs --panel ${options.panelUrl} --token-id ${node.daemonTokenId} --token ${options.token} --port ${node.daemonPort}`;
}

/**
 * Reconfigures an existing install against this node (no system changes).
 * Uses the global `spanel-daemon` binary that `install` sets up.
 */
export function renderConfigureCommand(node: Node, options: DaemonConfigOptions): string {
  return `sudo spanel-daemon configure --panel ${options.panelUrl} --token-id ${node.daemonTokenId} --token ${options.token}`;
}
